# FROM node:18-alpine AS builder
# RUN apk update
# # Set working directory
# WORKDIR /app
# RUN yarn global add turbo
# COPY . .
# RUN turbo prune web --docker

# # Add lockfile and package.json's of isolated subworkspace
# FROM node:18-alpine AS installer
# RUN apk update
# WORKDIR /app
# COPY --from=builder /app/out/json/ .
# COPY --from=builder /app/out/yarn.lock ./yarn.lock
# COPY --from=builder /app/turbo.json ./turbo.json
# RUN yarn install --frozen-lockfile


# FROM node:18-alpine AS sourcer
# WORKDIR /app
# COPY --from=installer /app/ .
# COPY --from=builder /app/out/full/ .
# COPY .gitignore .gitignore
# RUN yarn turbo run build --filter=web --include-dependencies --no-deps

# FROM node:18-alpine as runner
# WORKDIR /app
# COPY --from=sourcer /app/ .
# CMD [ "node", "apps/web/build/index.js" ]

FROM node:18-alpine
WORKDIR /app
COPY ./build .
CMD ["node", "index.js"]