version: "3.8"
services:
  backend:
    image: dayrim/whale-backend:latest
    ports:
      - "8888:8888"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_DOMAIN=${TELEGRAM_WEBHOOK_DOMAIN}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TELEGRAM_APP_ID=${TELEGRAM_APP_ID}
      - TELEGRAM_APP_ID_HASH=${TELEGRAM_APP_ID_HASH}
      - WEB_URL=${WEB_URL}
  web:
    image: dayrim/whale-web:latest
    ports:
      - "3333:3000"
  db:
    container_name: whale-db-container
    image: postgres:16
    command: postgres -N 200
    ports:
      - "${POSTGRES_PORT}:5432"
      - "8085:8080"
    volumes:
      - ~/db/data/whale-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
