apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    app: backend
  type: ClusterIP # You can change this to NodePort or LoadBalancer as per your requirement
