name: CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          # Replace with your registry's login URL if not Docker Hub
          # registry: your-registry-url.com

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: dayrim/whale-backend:latest
          # Add other parameters as needed

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: dayrim/whale-web:latest
          # Add other parameters as needed
